[{block name="minibasket_top_functions"}]
    [{if $oViewConf->isPaypalActive()}]
         [{include file="fatchip_computop_payments/fatchip_computop/minibasket_top_functions.tpl"}]
    [{/if}]
    [{$smarty.block.parent}]
[{/block}]
